<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BoneAI.Updater</AssemblyName><RootNamespace>BoneAI.Updater</RootNamespace><Version>2.2.0</Version><PlatformTarget>x64</PlatformTarget>
    <BONELAB_DIR Condition="'$(BONELAB_DIR)' == ''">$(BONELAB_DIR_ENV)</BONELAB_DIR>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader" HintPath="$(BONELAB_DIR)\MelonLoader\net6\MelonLoader.dll" Private="false" />
  </ItemGroup>
</Project>
